name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.x.x # use the explicit version number
        with:
          build: npm run build
          start: npm start
          browser: chrome
          headless: true
          record: true
        env:
          TZ: Europe/Zurich
          CYPRESS_standard_password: ${{ secrets.CYPRESS_STANDARD_PASSWORD }}
          CYPRESS_locked_password: ${{ secrets.CYPRESS_LOCKED_PASSWORD }}
          CYPRESS_problem_password: ${{ secrets.CYPRESS_PROBLEM_PASSWORD }}
          CYPRESS_glitch_password: ${{ secrets.CYPRESS_GLITCH_PASSWORD }}